### ISSUE TITLE
29v - Change margin placement of fig

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1104]
Placement of fig (small decorative hash-mark) seems to be left-middle (at least in TC), but it is actually in the right (or inline?)

Can you check on the placement/rendering here? Thanks!

**Comment by thuchacz** [comment]
As you have noted, this issue has to do with the margin block the figure was positioned in. The easiest fix is to decide that this is an addition, and we can add it before the beginning of the main text. However, with responsive pane resizing, we can't guarantee that the image will render in the right margin, only that it will render at the end of the line in question.

Since the solution @njr2128 tried above is not reflected in the current xml, I imagine it didn't work well, perhaps because of the "right-bottom" position marker. In any case, we need that figure adjacent to the word next to it in the line—it is an illustration, I think. In other words, we cannot put it in the right margin for the sake of mirroring the facsimile, because its importance to the text overrides its visual position, which is incidental.

**Comment by thuchacz** [comment]
I made the decision to make the figure x-small and to keep it at the end of the text that is currently positioned in the left margin. We can revisit this approximation of the page when we do a rendering read-through campaign.

Done.
