### ISSUE TITLE
Translation suggestions from WGM19: fol. 56r -  from M Spring re translation

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1143]
@thuchacz Not sure this was incorporated into your tasks?  I found a few translation tasks that did not seem to be assigned or done.  Please assign tasks to rest of Team if you wish.

1. ACCEPTED Marika S: fol.056r it states that ‘Lake takes long to dry in oil and for that reason one must grind glass among it. [alternative suggested translation; you have to grind some glass with it]. But one needs to choose crystal glass because it is neater. [Alternative translation suggestion; But you have to choose cristallin, because it is cleaner]
this use of “net” / “nettoyer” has nothing to do with disorder (neatness) but with the use of the best quality glass as opposed to a “dirty,” colored glass with a green or brown tint
SUGGESTION: cleaner

2. ACCEPTED: use peach stone, rather peach pit w.r.t peach stone black, as this is more commonly used in other treatises

3. ACCEPTED MS: ‘desiccative’ - ‘siccative’ would probably be better since dessicate means to remove water.  Change to "siccative"

**Comment by thuchacz** [comment]
This was not part of my tasks. I was assigned to articulate and implement the more complicated issues to come out of our conversation w M. Spring.
Spring's straightforward suggestions were implemented on the spot in our meeting by Clément.

**Comment by njr2128** [comment]
2 and 3 have been completed in earlier campaigns.

1 has not been done - @njr2128 will complete now

**Comment by njr2128** [comment]
UPDATE:
item #1 is actually on 57r

**Comment by njr2128** [comment]
**Summary of changes actually made:**
Lake takes long to dry in oil and for that reason one must grind glass among it. 
[alternative suggested translation; you have to grind some glass with it]
`one must grind some <m>glass</m> with it.` (to keep with standard translation of _il fault_)

But one needs to choose cristallin because it is neater. 
[Alternative translation suggestion; But you have to choose cristallin, because it is cleaner]
`But one needs to choose <m><fr>cristallin</fr></m> because it is cleaner.`

**Comment by njr2128** [comment]
completed
