### ISSUE TITLE
images from finalized annotations pre-FA16

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1151]
Sophie, Wenrui, etc., and whatever essays the team finalized in Summer 2019.

**Comment by njr2128** [comment]
The following annotations have been added to **media-full-list** because they were marked as finalized by M&K team member in Annotations-tracking:

1. ann_001_fa_14_CataldoVisco_Wax-Tallow
2. ann_003_fa_14_CarlsonKatz_MoldedRoses
3. ann_006_fa_14_CataldoVisco_CalcinedOysters
4. ann_008_fa_14_Mellon_ExcellentMustard
5. ann_011_fa_14_CataldoVisco_SandsandBinders
6. ann_027_fa_15_Zhao_ReversePaintingOnGlass

For all of these, links and image order were checked, and image permissions were logged.

**Comment by njr2128** [comment]
@ps2270 and @TillmannTaape, 
The following have unclear statuses in Annotation-tracking. Please clarify and, if ready, I will add to media-full-list.

- ann_007_fa_14_LandsmanRowen_SulfurAndAdditives
- ann_036_sp_16_Pitman_BlackColorForDyeing

**Comment by njr2128** [comment]
ann_007_fa_14_LandsmanRowen_SulfurAndAdditives
> has been completed. Images were renumbered and links checked. 

ann_036_sp_16_Pitman_BlackColorForDyeing
> TT will check status tonight and then NJR will implement

**Comment by TillmannTaape** [comment]
SJP annotation:

Fol. numbers need to be converted to <34r> format.
Use of "ibid." needs to be removed from footnotes.
Square brackets for figure callouts need to be replaced by parentheses.

Otherwise, the state of the annotation is now reflected in the metadata sheet.

**Comment by TillmannTaape** [comment]
NB I have not signed off on notes and bibliography because I did not at this point go through with a fine-toothed comb. But it looks good, apart from the ibid. Let me know if this a priority to do now.

**Comment by ps2270** [comment]
I assume you have catalogued media from my two essays? The only addition to that is that I am adding the lab videos at strategic points in Essay 2. I am almost finished with that, and will let you know then. I've asked MHS, but he has not yet answered me. If his essay doesn't go into the first release, I think it's ok.  
My only question is whether we should include Colin and Sarah's essay on Toulouse context in French.  I could ask if they could possibly finish it, but we can also simply let it go until later...perhaps that's best.

**Comment by njr2128** [comment]
Yes, got PHS' two essays.
I also catalogued the lab videos. If you want to link out, please use the
links I have in the* media-full-list* (rows 397-407) because then we don't
have to duplicate how many times we have the videos, which are large files.
As I catalogued those videos, Caroline and I tried to see where those
callouts in your essay might be but could not find them, so were waiting to
tell you that we have them when you are ready! You beat us to it.

We may have some flexibility in timing, so let us definitely keep a running
list of the "next" essays

**Comment by ps2270** [comment]
Should I be linking out or entering any metadata info for all my illustrations?

**Comment by njr2128** [comment]
Let's review together in-person tomorrow

**Comment by njr2128** [comment]
Discussed and reviewed during Oct 11 meeting. Finalized for now
