### ISSUE TITLE
3 latin words that need either Ed comments or Glossary

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1174]
Forgive me for passing this to you @TillmannTaape — but my brain is fried. I've just spent the last 4 hours going through the Latin Terms table, cross-checking, making all the missing editorial comments for the translations, and anchoring them across all versions. There are 3 problems left. Could I bother you to take care of these last few?

114r | pater noster | Left in original in TL w <la> tags. No translation.TO DO: add editorial comment translation or put in glossary | also on 103r, 4 times
-- | -- | -- | --

055r | semperviva | Left in original in TL w <la> tags. No translation.TO DO: add editorial comment (with translation??) | PLANT NAME | houseleek
-- | -- | -- | -- | --
055r | vermicularis | Left in original in TL w <la> tags. No translation.TO DO: add editorial comment (with translation??) | PLANT NAME | Not sure this needs  translation since it is an alternative name for "semperviva" (i.e. houseleek)

**Comment by TillmannTaape** [comment]
Bless you, of course!

pater noster: this was not tagged as Latin on 103r, and had in fact been treated as an English word by adding a plural s. I've tagged as Latin and removed the s. Alternative would be to translate "paternoster" which is an English word and remove Latin tags, although the explanatory comment "The Lord's Prayer" could stay (I only added it on the first instance since they are all in the same entry).

I added the comment for semperviva but not again for vermicularis – as you point out, it's the same plant.

**Comment by TillmannTaape** [comment]
Sorry I meant to tag @ps2270 to approve the pater noster solution.

**Comment by ps2270** [comment]
Take pater noster out of Latin tags, and keep editorial comment.

**Comment by TillmannTaape** [comment]
Done.
