### ISSUE TITLE
Annotation captions - information on M&K images?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1228]
Do we want "© The Making and Knowing Project" in the caption for every photo from the M&K Lab/Project? Do we care about nominal copyright of our photos?

I don't think I understand the pros and cons of this decision, so please weigh in, @njr2128 @tcatapano @thuchacz @TillmannTaape @Pantagrueliste

**Comment by thuchacz** [comment]
There is no obligation to have it—the project retains the copyright
regardless of whether we include the copyright symbol, though there is some
case law that suggests it is more defensible to have it displayed.
Regardless, from what I have been able to find, it is simply good practice
to include it (often with the year of first publication, which, for us, is
probably the semester year, since that's when the image was first posted to
Flickr).

I actually wonder whether we should amend the captions for all our Lab
photos to switch from:
Fig. 2. Tin with Etched Design. James Buckley, Making and Knowing Lab, 2018.
to
Fig. 2. Tin with Etched Design. James Buckley, © The Making and Knowing
Project, 2018.
or
Fig. 2. Tin with Etched Design. James Buckley © 2018 The Making and Knowing
Project.

There was an earlier time when the logic of "Making and Knowing Lab" was
meant to signal that these images were taken in the lab, but that is not
always the case, since some reconstruction work was done by our students at
home.

If we go with one of the proposed amendments, it would be a simple search
and replace in all the caption files for the first batch of essays—which
could be done in under an hour.

T.

**Comment by ps2270** [comment]
M&K captions: 
FINAL DECISION: (will involve some revision of captions if place is important)
Fig. 2. Tin with Etched Design. James Buckley, 2018.  Blah blah blah description. © The Making and Knowing Project

**Comment by ps2270** [comment]
We will also include the license, which we have decided is as follows (we can link this) (PENDING INPUT FROM MICHELLE WILSON)
© The Making and Knowing Project (CC BY-NC-SA) https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by njr2128** [comment]
From Terry:
https://www.lib.berkeley.edu/scholarly-communication/copyright
https://copyright.columbia.edu/content/dam/copyright/Precedent%20Docs/fairusechecklist.pdf
ALA fair use evaluator: https://librarycopyright.net/resources/fairuse/index.php
What this tool cannot do for you: This tool does not provide legal advice. It records the information you provide it as well as your own judgment on the fairness of the use. See the tool [disclaimer] for more information. Only a court of law can definitively rule on whether a use is fair or unfair. This tool does not assume or predict a court outcome.
since every fair use claim depends on the specific context of the intended use, you should contact your institution's copyright specialist or legal advisor with any questions you may have.
Publishing online is not the same as book bc of reuse
Fair use argument - cannot really make that judgement unless Columbia is allowing us to be that agent to take on the liability
Artstor
https://support.artstor.org/hc/en-us/articles/360021380333?article=iap-terms-and-conditions-of-use
https://support.artstor.org/hc/en-us/articles/360021187714-Images-for-Academic-Publishing

**Comment by njr2128** [comment]
decision reached, recorded in **annotation-workflow** GD doc, and implemented (or soon to be implemented)
