### ISSUE TITLE
review markup on 170v, esp surrounding fig in ups

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1314]

**Comment by njr2128** [comment]
related to #1243

**Comment by tcatapano** [comment]
move `<ups>` to contain `<cn>`:

https://github.com/cu-mkp/m-k-manuscript-data/blob/036672dcac1b4e175df35353d818275bbebd3b55/ms-xml/tc/tc_p170v_preTEI.xml#L16

this would be consistent with

https://github.com/cu-mkp/m-k-manuscript-data/blob/036672dcac1b4e175df35353d818275bbebd3b55/ms-xml/tc/tc_p170v_preTEI.xml#L130

**Comment by thuchacz** [comment]
Absolutely not. Do not do this. Look at the facsimile.

"ups" is tied to specific characters that are under the paper strips. Only
the "s" of "ecus" on 170v is under the paper strip. That's why coin wraps
larger than ups there.
The whole line of "Albertus magnus..." is under the paper strip. That's why
the ups wraps larger than the other elements there.

**Comment by tcatapano** [comment]
OK. Closing.
