### ISSUE TITLE
129v - rendering needs fixing

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1472]
TL, TC, and TCN all have different problems in rendering. @thuchacz I'm not sure this is about margin blocks or something else. Please check and then made a bug issue for Nick as appropriate.
thanks!

**Comment by njr2128** [comment]
See end comments in https://github.com/cu-mkp/making-knowing-edition/issues/257 to see the problem with the image in the margin. We believe it is because it is tagged as "top" and is thus bumping up to the previous entry's margin space. However, the marginal note from that entry is long and thus takes up space down the entire length of the margin - resulting in an overlap

**Comment by thuchacz** [comment]
This page has been extensively reworked. The rendering looks great.
Closing.
