### ISSUE TITLE
missing figure on 46r: markup problem

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1591]
Needs to be reviewed by M&K team why the figure does not show up in all three versions (tc, tcn, tl).
This appears to be a markup problem and NOT a rendering one

![image](https://user-images.githubusercontent.com/14779727/78368338-79a84500-7591-11ea-8b3c-8d0f5e3a0d4b.png)

**Comment by thuchacz** [comment]
Is it in any of the versions?

**Comment by njr2128** [comment]
Sorry, I should have been clearer! Thanks for the question.

markup has it in a margin in all versions (tc, tcn, and tl) but it does not render in any of them.
The corresponding mark on 46v is totally fine

**Comment by thuchacz** [comment]
@tcatapano @tcatapano 

This image doesn't render because it is just floating on the page between divs, not associated with any `<div>`. In fact, it has been surmised to be a bleed through from the following page, where "oil of sulfur" as a writing material is discussed and—we propose—experimented with. (NB: SJP includes these images in her Intro Essay.) In any case, is it possible to add the `<div>` from the next page (fol. 46v) to this page (fol. 46r) but not include a "continued/continues" attribute, so that they can be associated? And if so, should I be using the "part" attribute? or is that only used when there are multiple parts of the same div on the same page?

Thanks!!

**Comment by thuchacz** [comment]
Image added. `<div id="p046v_4"  categories="corrosives">` used for first time on 46r, and the main text on 46v is `<div id="p046v_4" part="y">`
