### ISSUE TITLE
Meaning/translation of “foeille de topasse”

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#171]
what does “foeille de topasse” mean? 

- on 102v “foeille de topasse, d’or ou d’argente”; 

- on fol. 120r: “lames de foeilles de pierrerie”
 
- PHS 2018: I think “foeilles de pierrerie” means the leaves of metal (foils?) that form backings for gems, so “lames de...” means sheets of these metal backing leaves.

**Comment by thuchacz** [comment]
See Ch. XVI on method of falsifying rubies in [Le Parfaict Ioaillier, ou Histoire des pierreries, 1644](http://bit.ly/2HRHGHA) that requires a red-colored metal leaf beneath sapphire, crystal, topaz, or fake diamonds to imitate the effect of rubies.

**5 RELEVANT INSTANCES:**

37r_3
**Foeilles pour** <del>le <ill/></del> **les <m>pierreries**</m>
<ab>Estant faictes, il ne les fault pas tenir dans aulcune <tl>caisse de <m>fer</m><lb/>
ne de <m>metal</m></tl>, car cela les faict tacher, mays en quelque boicte de</ab> [unfinished]

**Leaves for** <del>the <ill/></del> <m>**gemstones**</m>
<ab>Once made, one ought not to keep them in any <tl>case of <m>iron</m> or <m>metal</m></tl>, for this stains them, but in some box of</ab>

40v_1
Croix des <pro>commandeurs de <pl>Malte</pl></pro>
<ab>Ce beau <m>rouge clair</m> qui faict le champ de la croix<lb/>
blanche d'<m>esmail</m> est <del>sang</del> larme fine de <m>sang de <al>dragon</al></m><lb/>
destrempé en <m>eau de vye</m> ou bien <m>laque platte d'<pl>Inde</pl></m>,<lb/>
qui a mon advis se faict en <pl>Flandres</pl>, destrempée avecq<lb/>
<m>tormentine claire</m> &amp; <m>larme de mastic</m> &amp; posée sur une foeille<lb/>
d'<m>argent</m>, non pas de celle dont usent les <pro>painctres</pro> mays<lb/>
de celle plus espesse qui est brunie par <pro>ceulx qui font les<lb/>
**foeilles de pierrerie**</pro> <del>Av</del> ou par les <pro>orfevres</pro>, &amp; cella luy<lb/>
donne ce bel esclat.

[...] laid down on a <m>silver</m> leaf, not the kind which the <pro>painters</pro> use, but a thicker kind, which is burnished by <pro>those who make **foil backings for gemstones**</pro> <del><fr>Av</fr></del> or by <pro>goldsmiths</pro>, &amp; that gives it this beautiful brilliance.

102v_1
Paindre sur <m>cristal</m> ou <m>verre</m>
[...] Mays il le fault coucher peu à peu affin qu'il se monstre uny<lb/>
&amp; tout d'une couleur, &amp; ainsy des aultres couleurs. Aprés<lb/>
ilz mectent dessoubs une <m>**foeille de <m>topasse</m> ou une d'<m>or</m><lb/></m>
<m>ou d'<m>argent</m>**</m>

[...] But one needs to layer it little by little so that it appears even &amp; of one color, &amp; thus for other colors. Next they put underneath it a <m>**leaf of <m>topaz</m>, or one of <m>gold</m> or
<m>silver</m>**</m>.

120r_1
Medailles d’estampe par la <m>cire</m>
Tu peulx mouler en <m>cire</m>, meslée d'un peu de <m>rousine</m> pour estre plus<lb/>
dure &amp; ferme, le relief de ce qu'il te plaira, ou animal ou medaille,<lb/>
&amp; puys en faire un cave de <m>letton</m> ou <m>cuivre</m>. Ou bien <del>le frapper</del> <add>le mouler</add><lb/>
de relief <add>et le frapper</add> dans une <tl>plaste d'<m>estain</m></tl>, <del>Et pu</del> et puys le remplir<lb/>
de <m>plomb</m> &amp; braser. Essaye les <m>lames de **foeilles de pierrerie**</m><lb/>
moulé en cave pour <al>lesards</al> &amp;<exp>c</exp>.

You can mold in <m>wax</m>, mixed with a bit of <m>resin</m> so it will be harder &amp; firmer, the relief of whatever you please, either an animal or a medal, &amp; then, from it, make a hollow of
<m>latten</m> or <m>copper</m>. Or <del>hit it</del> <add>mold it</add> in relief <add>and hammer it</add> in a <tl>sheet of tin</tl>, <del><fr>Et pu</fr></del> and then fill with <m>lead</m> &amp; heat it. Try <m>sheets of **gemstone foil**</m> molded in hollow for <al>lizards</al> &amp;c.

129v_2
Animaulx gectés en <m>cuivre</m>
Essaye, <del>d</del> les ayans jectés en <m>cuivre</m>, de les brunir co<exp>mm</exp>e les<lb/>
<m>**foeilles de pierrerie**</m>, pour voyr s'ilz prendroient la couleur<lb/>
de mesme.

Try, <del><fr>d</fr></del> having cast them in copper, to burnish them like <m>**gemstone foil**</m>, to see if they take color similarly.

____

**NB: @thuchacz fix end punctuation and tags around line-break on 102v_1**

**Comment by thuchacz** [comment]
THU Recommendation: 
Foeilles pour les pierreries = Foil backings for gemstones
foeilles de pierrerie (x3) = gemstone foil (OR foil backings for gemstones??)
foeille de topasse ou une d'or ou d'argent = foil backings for topaz or one of gold or silver

**Comment by thuchacz** [comment]
Point to Whalley article in the GD.
DECISION
Foeilles pour les pierreries = Foil backings for gemstones
foeilles de pierrerie (x3) = gemstone foils
foeille de topasse ou une d'or ou d'argent = foil backing for topaz or one of gold or silver

**Comment by thuchacz** [comment]
Updated 37r_3, 40v_1, 102v_1, 120r_1, 129v_2 based on decision above.
Ensured gemstone foils were marked up as materials.
Updated glossary.
