### ISSUE TITLE
Translation of "smith's water"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#176]
“old smith’s water”

- Is this a technical material?
- Is this even a thing outside of Fr 640?
- Translate or leave in French?

**Comment by TillmannTaape** [comment]
Yes it's a technical term. Aqua fabrorum crops up here and there as an ingredient for surgical remedies, rendered as "smiths' water" in contemporary translations. [See Juhani Norri, Dictionary of Medical Vocabulary in English, 1375–1550.](https://books.google.com/books?id=madTDAAAQBAJ&lpg=PA1213&ots=M2xfVOA38J&dq=%22aqua%20fabrorum%22&pg=PA1213#v=onepage&q=%22aqua%20fabrorum%22&f=false).

**Comment by TillmannTaape** [comment]
Decision: since the recipe is kept in Latin in the TL, with an editorial note providing the translation, I have translated "old smiths' water", with an editorial note on the Latin term "Aqua fabrorum antiquae" explaining that aqua fabrorum is "smiths' water" (see my comment above). This should disambiguate that this is old water used by smiths, not water used by old smiths.
