### ISSUE TITLE
Translation/use of "pallete"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#178]
Decide what word to use in English:

- pallete is a painter’s palette, but also a palette knife. 

- In  French, it is a “small shovel”, so spatula or pallet knife is reasonable, although it can be of wood, which would not  come to mind if we translated it as palette knife.  

- “Pallet”  is used in English in the 16th c to mean a palette knife, so we could use that, but it calls to mind a straw bed (doesn’t it?).  

- Whatever we decide, it should be made consistent throughout. Just have to make a translation decision

**Comment by thuchacz** [comment]
THU searched for “palet” (3), “palle” (11), “palat” (0), “pallat” (0)

**THU RECOMMENDATIONS:**

- Would we prefer to use “palette knife” instead of “spatula”?
- Clearer connection of "palette knife" to French palette but OED doesn’t attest before 1760
- Cotgrave gives: “Lingell [=flat blade or spoon], tenon, slice, or flat toole wherewith Chirurgians lay salve on plaisters”
- TT: do you know what the English equivalent of this tool might be?
- OED “palette knife” does not include this medical sense explicitly

<img width="658" alt="screen shot 2019-03-08 at 07 16 41" src="https://user-images.githubusercontent.com/23508994/54028175-2a1afe00-4172-11e9-99bd-2b89312ce2ba.png">
<img width="618" alt="screen shot 2019-03-08 at 07 18 00" src="https://user-images.githubusercontent.com/23508994/54028218-56cf1580-4172-11e9-916b-30f8a66b24bd.png">

**Comment by thuchacz** [comment]
PHS DECISION: use "palette" or "spatula" depending on context.
