### ISSUE TITLE
replace xmllint with jing for travis validation check

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1787]
xmllint apparently does not catch invalid attribute values as defined in relaxng schema.

```
$ xmllint --noout --relaxng schema/ms-transcription.rng ms-xml/tc/tc_p001r_preTEI.xml 
ms-xml/tc/tc_p001r_preTEI.xml validates
```
jing does:

```
$ java -jar ~/Dropbox/xml/tools/jing/bin/jing.jar schema/ms-transcription.rng ms-xml/tc/tc_p001r_preTEI.xml 
/Users/terry/Github/m-k-manuscript-data/ms-xml/tc/tc_p001r_preTEI.xml:10:38: error: value of attribute "render" is invalid; must be equal to "full", "tall" or "wide"
```

**Comment by njr2128** [comment]
this is still a bug in xmllint (not catching invalid attribute values), so this should be considered

**Comment by njr2128** [comment]
For reference:

- https://relaxng.org/jclark/jing.html
- http://manpages.ubuntu.com/manpages/bionic/man1/jing.1.html

**Comment by njr2128** [comment]
As encountered in #1949,  
- travis removal #1947 and check the efficacy/completeness of Github Actions replacement
- tested by NJR pull requests #1957, #1955, and #1954 which all passed
- this, however, raised the issue of #1787 because no error was thrown for the schema missing attribute value of full (as in #1953 issue above)

xmllint does not catch the fact that `full` is a value for the attribute `margin` (fol 2v, TL only)

**Comment by njr2128** [comment]
@gschare, Install jing using `apt` and use for validation (tested by THC today on Unix machine)
Need to figure out what will be interpreted as "success"/"pass" because this is different from xmllint (error code is not 0 in jing)

**Comment by gschare** [comment]
I had an error both on my machine and on the GitHub Actions automated test when trying to install Jing. It was solved by first running `sudo apt update`.
