### ISSUE TITLE
Translation of "couleur" as flux vs. color

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#185]
Couleur (f.) = a substance to make metals flow more easily, a flux or liquifier. 

- We need to search all instances of “couleur” to make sure we have distinguished “color” and this substance.  

- See #123 "Check consistency of couleur": Mark as a material in all versions of the ms, and leave in French (and mark with Fr tag)

**Comment by njr2128** [comment]
See also #110 and #123 for markup of "or couleur/e" and "couleur/e" respectively

**Comment by TillmannTaape** [comment]
Search term: couleur

Editorial comment (added in TC, TCN, TL): 
_Couleur_ here refers not to "color", but to a flux or liquefying agent which makes molten metals flow more easily. From the verb _couler_ (to flow).

Instances of 'couleur' meaning flux rather than colour:
135r
135v
136r

Ambiguous:
137v. "Tu verras que tout  se dissoubdra co<exp>mm</exp>e <m>cire</m>, faisant force couleurs." – the ap is talking about making a flux here, but he could be describing a colour change in the making process here. Given the injunction to 'see'  (tu verras) and the plural of 'couleurs', I think this is more likely, so I am not tagging 'couleurs' as material here or inserting the editorial note.
