### ISSUE TITLE
Meaning of "artiste"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#194]
research on the meaning of “artiste” fols 62r, 62v, 65v, 162v

**Comment by ps2270** [comment]
Cotgrave: artisan, artist, and Master of art [meaning "of the liberal/university arts"]. 
DMF: Celui qui pratique un métier manuel (les arts mécaniques)" from 1405.
Littre from 16th c:
Nature faict naistre, ez nations moins cultivées par art, des productions d'esprit souvent qui luictent les plus artistes productions, Montaigne, I, 143.
[Après avoir cité un tour de la fortune] Semble il pas que ce soit un sort artiste ? Montaigne, I, 253.
La nature, dict-il, est un feu artiste, propre à engendrer, Montaigne, II, 278.
Choses lesquelles se proposent tous bons ouvriers et artistes en cest art [de distillation], Paré, XXVI, 4.

In English, the most frequent use of artist in the 16th-c is as a skilled artisan, but it is just beginning to be used as someone skilled in the CREATIVE arts (in our sense).

Some of these entries, 62r, 62v, 65v (Blanc et noir) are about an apprentice becoming an "artiste," we could use artisan or artist. On fols. 65v (Paindre...) and 162v, "artiste" seems to be a modifier, and I guess could be translated as "artistic" or "skilled", but I think we should translate as "artistic".  
Also, I will enter this as a glossary item, and we should probably have an editorial note on these instances that says:
"artist and artistic in this period referred both to skilled artisanal work and was just beginning to be used in the sense of skilled creative artistic work in a more modern sense."

**Comment by ps2270** [comment]
From off-Github conversation:
TT: “artiste” is an adjective in the French, but I like “artist’s touch” (or perhaps better “line”/”stroke”) as a translation because it conveys the idea of the skill of a practised artist, whereas what exactly is meant by “artistic” here seems less clear and might require some unpacking. 

CAG: I agree with TT. Artiste as an adjective in the sense of “skilled,” “professional.” (Französisches Etym. p.346  “qui est fait avec habileté” 1575 )

THU: this might end up needing <pro> tags

TT: How about “you will acquire a skilled line/stroke”? Too unclear?

**Comment by ps2270** [comment]
TT & PHS decided to translate "artiste" as artist, as it already is.  No changes needed to any of the nouns. This is already entered in the glossary by PHS.  No editorial note needed. TT is changing the translation on 65v to "you will acquire an artistic line/stroke & will render your hand nimble."
