### ISSUE TITLE
List of Entries - incorrect categorization - fol. 13v_4

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1951]
Fol. 13v_4 "Snakes" is listed under the category "casting" but the entry has nothing to do with casting. It is also tagged with animal and Greek, which is appropriate. It would better be categorized under "animal husbandry". Here is the entry for reference:

It is said that if one calls a snake in Greek, saying ΟΦΗ ΟΦΗ,*
it will flee. Likewise, if one nom calls a swine in Greek, y ïon,*
it will come.

**Comment by ps2270** [comment]
Or daily life. But neither husbandry and daily life are really apt.

**Comment by njr2128** [comment]
I think "animal husbandry" and "household and daily life" are the best fits we have for this. I imagine it was originally categorized as "casting" because we associated it with other entries that discuss catching animals for casting.

I will revise this entry to have the categories "animal husbandry" and "household and daily life"

**Comment by njr2128** [comment]
done
