### ISSUE TITLE
Translation of "graver"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#201]
Graver = to engrave or etch depending on context – can it also be ‘carve’ as is currently translated eg. in Founders of small tin work (80v)?

**Comment by thuchacz** [comment]
searched for "grav"

translated relevant words as "engrave" or "etch" depending on context.

See entry p004v_3 (fols. 4v-5r) for an instance in which both are used, and "engraving" takes the sense of "carving" into the varnish ground covering an iron object.

On 80v (founders of small tin works), I changed "carve.. on stones" to "engrave," since the latter includes the sense of incising and also has a (now obsolete though related) sense of cutting into hard material (See OED "engrave" 2a). Other instances of "carve" became "engrave" or "etch"
