### ISSUE TITLE
Translation of "plat de souldure"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#361]
(from PW18 tracking)

Keep in French? Consult with @ps2270 

See p028v_1 "Pinitiers"/"Peweters"

**Comment by TillmannTaape** [comment]
In the current tcn, "plat de souldure" on 28v has been broken up with a comma, as follows:

ilz y<lb/> font du meslinge de restes de plats, de <m>souldure</m><lb/> &amp; d’<m>estaim commun</m>.

This makes much more sense to me, and is in fact reflected in the translation:

in this they often mix in leftovers from <m>plates</m>, <m>soldering</m> &amp; <m>common tin</m>.

"Soldering" should be changed to "solder" – I will create a new issue to check for consistency of "souldure".

@ps2270 "plats de souldure" is still in the glossary, with the note keep in Fr. Shall I delete this entry since we now think that this is not one phrase?

**Comment by ps2270** [comment]
Yes, please.  Approved.

**Comment by TillmannTaape** [comment]
Done.
