### ISSUE TITLE
Translation of "Cendrée"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#364]
(from PW18 tracking)

Kept in French?

See p040v_3 "Metal"/"Metal"

**Comment by TillmannTaape** [comment]
Yes I think it should be kept in French in p040v_3 because we don't know what it is. The vocab says "Cotgrave defines it as a silver flux", but this is not at all clear to me from Cotgrave's entry.

@ps2270 do you know anything more about this?

two other occurrences are
13v "cendrée d'azur" translated as "azurite ash"
70r "terre cendrée" translated as "cendrée earth"
Both translations seem reasonable given what we do and don't know.

**Comment by ps2270** [comment]
I agree that flux is not the correct translation. Please  leave it in French. Can you please write a glossary entry based on Cotgrave, and DMF: "Métal réduit en petits fragments (gén. destiné à la fonte?
thanks.

**Comment by TillmannTaape** [comment]
On 40v it refers to a separation of a tin alloy, so the following meaning from Cotgrave seems more apt than the DMF definition.

Editorial note: Cendrée here likely refers to a method of melting and purifying metals in ashes (see Cotgrave).

I added this ed. note to the glossary. @ps2270 please review.

**Comment by ps2270** [comment]
Reviewed. Approved.
