### ISSUE TITLE
Translation of "Passe solitaire"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#380]
(from PW18 tracking)
"Passe solitaire" has been left in french.

Is there a suitable translation? 
Make consistent.

See p050v_1

**Comment by thuchacz** [comment]
MYSTERY BIRD:

- Cotgrave: "a little black-brown Owsell (or bird like an Owsell) thats ever alone, or if in any companie, with Sparrowes, among stone walls, or on the tops of houses, where sometime she singeth prettily."
- NB:  OED "ouzel" = 1.a European blackbird (Turdus merula); 1.b Ring ouzel (Turdus torquatus); 2. birds resembling the blackbird

- French naturalist Georges-Louis Leclerc, Comte de Buffon (7 September 1707 – 16 April 1788) notes in his 36-volume "Histoire naturelle" that the "merle solitaire" was known in France also as the "paisse solitaire." Description of the bird Vol. 3, p. 358–62, makes clear the rock/architecture habitat.
- Bouffon's bird also described in Bechstein, The Natural History of Cage Birds (1838), entry on "The Solitary Thrush" (p. 203)
- very recent distinction made between the family Turdidae (true thrushes) and Muscicapidae (Old World flycatchers); both families include birds commonly referred to as thrushes. Since European Turdidae build nests exclusively on tree branches, this family can likely be excluded

- modern "rock thrushes" covers the genus Monticola of the Muscicapidae family
- "passe solitaire" may be identical to the modern Blue Rock Thrush (Monticola solitarius; formerly Turdus solitarius—both given in Linneaus 1758)

THU recommendation: translate as "rock thrush" (thus capturing the genus) and add editorial note since there is but one instance of "passe solitaire" in the manuscript

**Comment by thuchacz** [comment]
See also: Pierre Belon, L'histoire de la nature des oyseaux, avec leurs descriptions, et naïfs portraicts retirez du naturel / escrite en sept livres (1555), chapter XXX on "paisse solitaire"
https://archive.org/details/hin-wel-all-00001828-001/page/n354

**Comment by thuchacz** [comment]
Paul J. Smith's "Passer solitarius: Tribulations of a Lonely Bird in Poetry and Natural History, from Petrarch to Buffon" (Brill, 2018) suggests that Brisson and Bouffon successfully identify the "passer solitarius" as the "alpine accentor" in the later 18th century. See doi:10.1163/9789004367432_018 

NB: the "passer solitarius" is mentioned in Psalm 101 (102).

NEW THU RECOMMENDATION: call it the "solitary sparrow" and put Smith's article as an editorial note.

**Comment by thuchacz** [comment]
DECISION:
Leave in French and add editorial note

**Comment by thuchacz** [comment]
Updated glossary.
Added editorial note to TC/TCN/TL of 50v
