### ISSUE TITLE
p037v_2 inconsistent use of "bois" by AP?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#384]
(from PW18 tracking)

p037v_2 | p037v | Vitrier | Glassmaker
-- | -- | -- | --

AP uses "bois" in the middle of the recipe even though he seems to be talking about glass throughout

Assess what is happening here

**Comment by thuchacz** [comment]
Appears to be an error: A-P writes "wood" when he means "glass":

p037v_2

Vitrier
Aulcuns ne chargent poinct de <m>gris d'escaille</m> le <m>verre</m> pour<lb/>
travailler d'aprest, ains trassent sur le <m>verre net</m> avecq<lb/>
du <m>noir à huile</m>. Mays il fault bien que le **<m>bois</m>** soit<lb/>
<m>desgraissé</m>, car s'il a tant soit peu de <m>graisse</m>, la couleur<lb/>
n'y prendra aulcunem<exp>ent</exp>.

Glassmaker
Some do not saturate the <m>glass</m> with <m><fr>gris d'escaille</fr></m> for working as primer, but trace on the <m>clean glass</m> with <m>noir à huile</m>. But it is very necessary that the
**<m>wood</m>** be rid of <m>grease</m>, because if it has even a bit of <m>grease</m>, the color will not take on it at all.

THU suggestion: leave as is and add editorial comment about the likely error.

**Comment by thuchacz** [comment]
NB: THU wrote to Isabelle Lecocq (Stained glass researcher at Belgium's KIK-IRPA) on morning of April  1 to enquire whether degreased wood could ever be necessary in stained glass making.

**Comment by thuchacz** [comment]
DECISION:
Leave as "wood" and add editorial comment about possible error or interpretations. But wait on response from Isabelle

**Comment by thuchacz** [comment]
Isabelle agreed that the a-p likely did not mean to write "wood." Added editorial note to TC/TCN/TL.
