### ISSUE TITLE
Check/implement semantic markup of entries in latin

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#408]
(from PW18 tracking)

Semantic markup has not been signed off by most recent PW for sections of entries in latin:

p170v_3 | p170v | Pour preserver | For preserving
-- | -- | -- | --

p001r - NA | p001r | LIST | LIST
-- | -- | -- | --

**Comment by TillmannTaape** [comment]
searched for "`<la>`" to find all words/passages in Latin, in all three versions.
Checked and revised markup.
There were more la tags in TL than TC/TCN, because "aquafortis" had been erroneously tagged as a Latin word (it is an English word, and the original term was French in each case). This has been corrected.
