### ISSUE TITLE
Translation of "canulle"

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#417]
Current protocol is to translate "canulle" as "thin cane" (e.g. for cages, 6v). This is awkward, especially when it comes to translating "grosse canulle" (currently "large thin cane").
MHS in the vocab suggests "pipe" as an alternative, and the context suggests that they are indeed hollow. Can we use this instead? Or what about "rod"?

@ps2270

**Comment by ps2270** [comment]
Cotgrave:  little cane, pipe, reed or hollow straw, so I don't know why we had "thin".  We should change the glossary entry to take out the "thin" and give more of Cotgrave's definition, http://www.pbm.com/~lindahl/cotgrave/search/156l.html.
DMF - implies use as pipe or straw
The other instance on 66v is now trans as "tube"
Thinking aloud: I think we can leave as "cane" altho caneworking in glass today implies solid rods of glass, whereas Cotgrave is insistent on the hollowness as a feature of "cannule".  We could supp with "small hollow" in the first instance, then translate as canes in all further instances.  Or we could have an editorial comment. Or we could change to pipe or straw or tube. Tube is good French by 15th c, but not in OED until mid 17th-c.  Interestingly, "cane" in OED in 16thc does imply "hollow" because it's an actual plant reed. Which makes one wonder if on 66v, the a-p was using an actual reed (so our "tube" gives a very different connotation).
Decision: change glossary entry.  6v: Trans as "cane."  Supp with "small hollow" in first instance, and trans as cane for the rest of 6v;
 66v: change to "hollow cane" (leave the small).
I realize this is translating for meaning in a way that contravenes "consistency", which is the way we have been approaching this, so if you think this is too much of a departure, please don't hesitate to speak up.

**Comment by TillmannTaape** [comment]
Changes made as per PHS discussion above.

**Comment by tcatapano** [comment]
Im trying to figure out the sequence of events for this issue to verify the master branch did not get corrupted. Re-opening.

**Comment by tcatapano** [comment]
Im particularly concerned about this commit: d4806ce1b3f445

**Comment by tcatapano** [comment]
@ps2270 @TillmannTaape @njr2128 I *think* it's OK to just redo the fixes for tl_p006v and tl_p066v as these are the only files that currently differ between the issue417 branch and the master branch. And Im presuming that the master branch is correct *except* for the problems with these files. If someone could verify that, we can go ahead and merge the fixes for tl_p006v and tl_p066v back into the master branch.

**Comment by tcatapano** [comment]
@TillmannTaape just to be safe, can you review tl_p006v in the master branch to make sure its ok? It's not about you, it's me ;-) Im worried Im doing something wrong in the conflict resolution.

**Comment by TillmannTaape** [comment]
@tcatapano I pulled the master branch and checked tl_p006v, it looks right!

**Comment by ps2270** [comment]
Tillmann,
Can you please let me know what happened with this issue, and close if it should be closed?

**Comment by TillmannTaape** [comment]
Yes we resolved those conflicts.
