### ISSUE TITLE
cimolée?

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#470]
In **tl_p071v_preTEI.xml**, _cimolée_ is tagged as a French word and a material, but TC and TCN make no use of this word, they both mention "la moulée".

Could not find any definition of cimolée, and I don't understand where it comes from: is it an error?

**Comment by ps2270** [comment]
Yes, on 71v, it must be an error. In terms of changing the translation, here is what we now have in the glossary (after I added the info about 71v--the rest was already there):
Moulée, moullée (f.) = ?
71v, it refers to a type of “sand” for molding that is the byproduct of sharpening knives and scissors (?), but could find no information, occurs twice on fol. 73r, where the scribe has left it blank and the a-p has filled in the word
On 73r (where I can only find it once??), it has been translated as fuller's earth, which is wrong.  
CAG: can you please see if you can find more information about this material in order to translate it differently?  If we cannot, we'll need to change translations of 71v and 73r to leave it in French.

**Comment by Pantagrueliste** [comment]
Cannot find information. Leaving it in French in 71v and 73r.
