### ISSUE TITLE
enilanroc

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#480]
Header of 12v_3
This is the backward spelling of FR "cornaline" (= EN carnelian)

How do we want this in the TL?
For whitening nailenrac — i.e., translated as "carnelian" but spelled backward?
For whitening <fr>enilanroc</fr> — i.e., left as it is but now with <fr> tags?
In either case, I think we need to add an editorial comment about it being written backwards.

TT & Colin have dealt with similar situations. We should be consistent in how we treat this ever-so-cryptic writing.

**Comment by ps2270** [comment]
Decision:
For whitening enilanroc — i.e., left as it is but now with tags. [what tags?]
We need to add an editorial comment THAT NOTES THAT IT IS CARNELIAN [I.E., CORNALINE] written backwards.

**Comment by ps2270** [comment]
@TillmannTaape

**Comment by TillmannTaape** [comment]
That is not what we've done in other cases of backwards writing, e.g. the 'horrible poison' entry, where we translated to English and then wrote it backwards. This makes sense to me, as there seems no reason to not translate a word just because it is written backwards; and writing it backwards in translation keeps the fun and perhaps also underlines the futility of this as a 'code'. 

So I would suggest "For whitening nailenrac", with appropriate tags (material I think), and a note that this is carnelian written backwards.

**Comment by ps2270** [comment]
Ok, I'm persuaded.  Go ahead and do that.

**Comment by TillmannTaape** [comment]
Are we sure we want to translate as carnelian? The vocab says to translate as "cornaline", citing Cotgrave, to maintain the ambiguity.

**Comment by ps2270** [comment]
Ah, ok. Cornaline it is

**Comment by TillmannTaape** [comment]
translated as "enilanroc" and anchored the following comment in all three versions:

""Cornaline" written backwards. According to Cotgrave, "cornaline" was used in both French and English, denoting a flesh-coloured stone. It likely refers to what we would now call carnelian."
