### ISSUE TITLE
Eau de vye

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#502]
Eau de vye has been left in French in the TL.  We decided to translate as eau-de-vie in English.  Search TL to change any remaining French instances to  eau-de-vie and remove French tags.

**Comment by TillmannTaape** [comment]
I don't get anything when searching the TL  for "vye". Looking for "eau" and "vie" I've only found "eau-de-vie", only one of which had French tags which I removed.

@ps2270 do you have a folio number for eau de vye? It may be that this has already been done and you're seeing this because you're looking in the edition which isn't up to date with Github.

**Comment by TillmannTaape** [comment]
Yep Tianna did this in #92!

@ps2270 We should find a way for you to at least view the most up-to-date version; or ask Nick when the edition will pull from Github rather than GD.
