### ISSUE TITLE
Mareschaulx in the vocab list

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#520]
@ps2270 
"Mareschaulx" appears twice in the vocab list (one is out of alphabetical order)
ACTION: consolidate

Keep in mind:
"Mareschaulx" is translated as "farrier" on 94v and 95r
It is left in Fr in 92v_2 ("old water from mareschaulx")

NB: "ferrier" on 115v has been translated as "farrier" in the TL—is this correct?

**Comment by ps2270** [comment]
Decision: translate all instances of mareschaulx as "farriers", i.e., 50v, 92v, 94v, 95r.  PHS has corrected and consolidated the glossary entry.
"Ferrier" on 115v should not be "farrier."  I'm not sure this whole line has been transcribed correctly because it is partly under the paper strip.  @TillmannTaape please have a look at it--the very last line on 115v and see what you think.  If it needs re-transcribing/translating, let me know.
While changing this on 115v, please correct the following on 116r:
"burning the plants, flowers, and animal parts remain inside"
should read
"burning the plants, flowers, and animal parts which are left inside"

**Comment by TillmannTaape** [comment]
Re "ferrier": I think it reads "moules des fleurs" not "des ferriers" – this also makes much more sense because he goes on to explain that these molds need to be fired twice to burn the flowers. I'm changing this provisionally across all versions but added a query to Marc's paper strip check list.

I've changed all instances of "mareschaulx" to "farriers"
