### ISSUE TITLE
Translation of "madre"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#600]
On 71r, there is an entry called "bois madre" in which elm root's "belle madreures" are discussed. "Madre" is left in french tags, "madreures" is translated as "streaks."

@ps2270 @TillmannTaape @Pantagrueliste 
**QUESTION:** Can we just change the heading to "Streaky wood"?

TCN:
```
<head><m>Bois madre</m></head>
<ab>L'<m><pa>orme</pa></m>, en sa racine noueuse, a de belles madreures
diversifiées de<lb/> gris et de noir,

<head><m><fr>Bois madre</fr></m></head>
<ab>The <m><pa>elm</pa></m>, in its knotty root, has beautiful streaks
diversified with grey and black
```

**Comment by TillmannTaape** [comment]
I think it should be "bois madré".

Cotgrave: "Madré – (Of wood) whose grain is full of crooked and speckled streakes"

We could translate "wood with streaked grain"?

**Comment by TillmannTaape** [comment]
The vocab currently has

keep Fr., i.e. “bois des loupes et racines d’orme, de frêne, de bruyères et d’autres arbres et arbustes à bois veiné (particulièrement employé pour faire des vases à boire)”

I think it makes more sense to read "madré" as an adjective modifying "bois" rather than as a noun referring to a specific type of wood (which, in any case, no doubt takes its name from the "madreures" in the grain).

**Comment by ps2270** [comment]
Please translate as 
Wood with streaked grain

I changed the Glossary entry 5/21/19

**Comment by TillmannTaape** [comment]
Changed tl to "Wood with streaked grain"
