### ISSUE TITLE
cendré(e) d'azur

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#602]
**INCONSISTENCY:**
"cendré(e) d'azur" is translated on 13v as "azurite ash" but kept in French on 129r. "cendre d'azur" has been kept in French on 62r.
Moreover, "cendre," where it refers to "cendres d'azur" on 11r, has been translated as "ash."

**Glossary:**
- Cendré(e) d’azur =  keep Fr., i.e. “azurite ash”?
Godefroy. Cotgrave: the whitest kind of azur? Cf. Azur de cendre (m.) = “azurite ash”( fol. 059r) — Jo Kirby, Susie Nash and Joanna Cannon (eds.), Trade in Artists’ Materials: Markets and Commerce in Europe to 1700 (London, 2010), p. 445. — HW, GC, SD 21/06/2017 (fol. 40v). Both the calcine chalk and charcoal that crucibles are made of, and shop sweepings (dross etc) in a goldsmith’s shop and it is purified by this method. (PHS). 
- Cendres (f. pl.) = “azure ash” — Cf. Azur de cendre (m.) = “azurite ash”
(p011r, p013v) See Spring 2016 annotation on azure enamels 

**QUESTION:**
Should we translate this across the manuscript?
@ps2270 can you please adjust the glossary to your decision and perhaps fold these two glossary entries together?
@TillmannTaape Do you have opinions here? Also, should "cendre d'azur" on 62r of TCN get an accent to become "cendré d'azur"?

**Comment by TillmannTaape** [comment]
Cendrée: I think this should be kept in French throughout. It may refer to crucible material and furnace sweepings as per PHS's suggestion above (which should be moved from the "cendrée d'azur" entry to the general "cendrée" entry above I think), to the method of purifying metals in ashes as per Cotgrave, or to the product of that process. We should have an ed. note to that effect.

Cendrée d'azur: I'd suggest `<fr>cendrée</fr> of azure` in TL, with the note for Cendrée, with an addition to say that this might be azurite ash (if we still think that's accurate).

Azur de cendre: "azurite ash", with Kirby et al. reference in glossary.

Cendre(s) d'azur: "azure ash" – because we can't be sure it's the same as azur de cendre, i.e. specifically azurite.

I don't think "cendre" with single e should be changed to "cendré" – "cendrée" with two e seems to be a separate thing (see above).

**Comment by ps2270** [comment]
Agreed. Thanks.

**Comment by thuchacz** [comment]
Implemented:
"cendrée" kept in Fr. Added ed. comment c_040v_01
"cendré(e) d'azur" = "<fr>cendré(e)</fr> of azure. Added ed. comment c_013v_04
"cendre(s) d'azur" = "azure ash"

**PROBLEM**
NB: "Azur de cendre" does not exist in the TL, so the glossary entry for it (which references Kirby et al.) is kind of useless. Do we want to rethink where the Kirby reference fits?? Or these translations?

**Comment by ps2270** [comment]
You say " NB: "Azur de cendre" does not exist in the TL," but do you mean the ms.? If it doesn't exist in the ms, the glossary entry should be for "cendre(s) d'azur", and should reference Kirby et al, noting that the a-p uses cendre d'azur, rather than azur de cendre, but context seems to indicate that he means azure ash by it.
Make sense?  @TillmannTaape can you please revise glossary entry?

**Comment by thuchacz** [comment]
Sorry. Yes. "Azur de cendre" does not exist in the Ms.
@TillmannTaape can you tweak glossary for this and close out?

**Comment by TillmannTaape** [comment]
Done.
