### ISSUE TITLE
Saphires "de treille"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#627]
See excerpts below. "de treille" — as qualifier of "saphire" — is left in French. Later in the entry, it is translated as "of a trellis." Is it necessary to keep the first instance in French? I know it makes for an awkward translation... perhaps a sup would be needed ("One finds sapphires that one calls trellis `<sup>`sapphires`</sup>`...)

```
<id>p038r_1</id>
<head><m>Saphir</m></head>
<ab>Il se trouve des <m>saphirs</m> qu'on appelle de treille, pource qu'ils sont<lb/>
percés et qu'on dict que certain <pro>roy</pro> en avoict faict certain
ornem<exp>ent</exp> en forme<lb/>
de treille, co<exp>mme</exp> seroict peult estre l'escran de
<pn>Charlemaigne</pn>, ainsy nommé, au<lb/>
tresor de <pl>Saint Denis</pl>

<ab>One finds <m>sapphires</m> that one calls <df><fr>de treille</fr></df>, because they are pierced and it is said that a certain <pro>king</pro> had made from these a certain ornament in the shape of a trellis, that would be thus named the Screen<comment>c_038r_01</comment> of <pn>Charlemagne</pn> in the
treasure of <pl>Saint Denis</pl>
```

**Comment by ps2270** [comment]
I think we should translate in both instances.`
New wording in caps here:
<ab>One finds <m>sapphires</m> that one calls OF THE TRELLIS<df><fr>de treille</fr></df>, because they are pierced and it is said that a certain <pro>king</pro> had made from these a certain ornament in the shape of a trellis, that would be thus named the Screen<comment>c_038r_01</comment> of <pn>Charlemagne</pn> in the
treasure of <pl>Saint Denis</pl>`

**Comment by thuchacz** [comment]
Change implemented. Issue closed.
