### ISSUE TITLE
esmouler

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#681]
"esmouler" isn't in the glossary.
This is an issue for me at the moment because on 71v, we have the deletion of "moulent" in favor of "esmoulent," but both are translated as "mold". Is this correct?

```
<head><m>Sable</m></head>
<ab>La <m>moulée</m> est fort bonne pour gecter en <m>cuivre</m>, mays il ne<lb/>
fault prendre de <m>celle des <pro>cousteliers</pro></m>, car ce n’est
que <m>vase</m>,<lb/>
mays de celle que font ceulx qui <del>moulent</del> esmoulent les grands<lb/>
ciseaulx.</ab>
```
```
<head><m>Sand</m></head>
<ab>The <m><fr>cimolée</fr></m> is very good for casting in
<m>copper</m>, but one ought not take <m>the one from
<pro>cutlers</pro></m>, because it is only <m>sludge</m>, but rather the
one of those who <del>mold</del> mold large shears.</ab>
```

"esmouler" also comes up (conjugated) on 94v and 95r (x2) — and nowhere else in the Ms.
On 94v, "esmoulues" = "milled"
On 95r, "esmoulues" = "ground"; "esmoulent" = "grind"

Can we come to a consistent translation? "Grind" seems to work well, even with the example of the shears on 71v. Agreed?
And does this need a glossary entry?

**Comment by TillmannTaape** [comment]
Esmoulent, esmoulu etc. are probably all forms of esmoudre rather than esmouler (see Cotgrave esmouldre), meaning to grind, whet, sharpen etc. I agree that 'grind' works well. I've updated the glossary accordingly and changed the TL to 'ground' on 94v to be consistent, and on 71v.

The real puzzler is "esmouler" in a deletion on 116r. In the current TCN it is "desmouler" but I think it should be "d'esmouler" because it is corrected to "d'esmailler" so it would make sense that they would have the same grammatical structure. DMF has "mouler" as a variant form of "moudre", so my best guess it that "esmouler" is a variant of "esmoudre" with the same meaning; so I'm going to change the deletion on 116r from "unmold" to "grind", since we have no support for "unmold". In any case, it is a deletion, and the confusion between "d'esmouler" and "d'esmailler" is no doubt a phonetic one.
