### ISSUE TITLE
"plane" and its various meanings (in Fr and in En)

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#692]
**GLOSSARY:**
Plane (f.) = “plane”, as distinct from “rabot” = joiner’s plane
	See Cotgrave. p094r_1 (CD TT)

**PROBLEM: Glossary does not adequately reflect the meanings of FR "plane"**
FR "plane" shows up 9 times in the Ms—30v (x3), 95v (x3), 96r (x3)—has been translated nearly throughout the Ms as EN "plane," which is used to mean either:
b) an iron tool to polishing tin (30v)
c) a blade with two handles (i.e., a "draw knife," per comment: c_095v_07) (95v, 96r)

On 30v, the 3 instances of FR "plane" have been kept in French—likely because we don't know what the English word for that polishing blade is.

NB: There are 14 instances of the English word "plane," which also encompasses the meanings above as well as:
d) a planar surface ("plan") (e.g., 16r)
d) a joiner's plane ("rabot" / "ribot") (e.g., 10r / 96r)

**TO DO:**
- update the glossary with more specific information about what is meant by "plane"
- decide whether the instances on 30v (and/or those on 95v/96r) should be kept in French
- implement

**Comment by TillmannTaape** [comment]
Glossary updated as follows:
1 | plane (woodworking tool)
2 | a specific type of plane called a draw knife, described on fol. 95v
3 | a tool for burnishing tin plates, described on fol. 30v

I'd suggest we leave the rest as it is: in French on 30v, because we're not sure what the English term is; translated "plane" on 95v/96r because he is clearly describing a type of plane for woodworking (unless someone has hard objections to a draw knife being a kind of plane).

**Comment by TillmannTaape** [comment]
@ps2270 please review suggestion above.

**Comment by ps2270** [comment]
on 30v, it sounds like it's a EN plane made into a burnishing tool by adding leather and putty. Interesting. But I think we should leave that in FR. 
I think all the suggestions above are fine.

**Comment by thuchacz** [comment]
Okay. Closing.
