### ISSUE TITLE
add <corr> tags to TCN where "il" in TC was silently changed to "ilz" in TCN

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#748]

**Comment by ps2270** [comment]
From Marc:
 I am quite surprised at the different count: as you say there was no decision to normalise, and I am supposed to have checked all of tcn at one point so I can't see how so many zs could have been thrown in later. Has the difference been checked against the manuscript, at least on a selection, just to make sure it's not a problem in tc?
The lack of matching is not at all unusual, since in many cases the difference would not be audible. The ap's ability is very good, but with ordinary carelessness about such matters. 
Action item: sample some of the added "ilz" in the facsimile against the tc and tcn

**Comment by TillmannTaape** [comment]
I think the result can be explained by my search parameters: I must have got those numbers by searching for "whole words only," which excludes "quilz" etc. in the TC, but not in the TCN, where it's separated by an apostrophe ("qu'ilz"). 

Repeating the search for just the string "ilz", I get 405 in TC and 407 in TCN, so only 2 differences.

**Comment by thuchacz** [comment]
Well that's somewhat of a relief! Well, it will be comparatively simple
enough to figure out where that discrepancy is. I wonder, actually, if the
difference can be accounted for by the "corr" tags that were removed the
other day...

**Comment by ps2270** [comment]
From Marc: Whew that’s a relief!

**Comment by TillmannTaape** [comment]
I've reinstated the two editorial `il<corr>z</corr>` we removed. The count is now 406 in the TCN vs. 405 in the TC, so we've still got one discrepancy. I'm not sure how to locate it. It may not matter too much.

**Comment by thuchacz** [comment]
DONE!!

Only discrepancy in "ilz" usage is 58v, where we have appropriately changed an "ilz" in the TC to `<corr><del>z</del></corr>` in TCN.

I FOUND THE MISSING "Z"!! It was on 107r — there was a plural verb with a singular "il" that had never been corrected in the TCN.

See my work in the GD spreadsheet entitled "ilz TC v TCN"
