### ISSUE TITLE
107r need ups tag?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#769]
Perhaps to be checked with MHS.
There is an editorial comment that "ending written underneath" for this p106v_2 left marginal note:
>ʘʘ
Pesant co{mm}e auparava{n}t
...
froid mesle et
moule Car tant
plustost tu **lemployeras***
apres sa cuite
tant plustost il
faict prise

Which has this markup:
>plustost tu lemployeras`<comment>c_107r_01</comment><lb/>`

**Comment by njr2128** [comment]
Similar situation on the same folio, p107r_1

> ...liaison au sable et pourcequil ne se brusle point il faict
que le sable soubstient le fœu sans se fendre & crever **Aultre{ment*}**
sans luy...

which DOES have ups tag:
>... crever Aultr`<ups>`e`<exp>`ment`<comment>c_107r_05</comment></exp></ups><lb/>`

**Comment by thuchacz** [comment]
@njr2128 There is no <ups> necessary. The editorial comment attached to the marginal block for entry p106v_2 on 107r refers to the ending of a conjugated verb that the author-practitioner has written below the stem of the verb, NOT below the paper strip (have a look at the facsimile). The other instance you point to does need and has a <ups> tag. Because of that markup, I think you can delete the editorial comment about the end of the word being under the paper.

I am closing this issue.
