### ISSUE TITLE
review markup/rendering of list on 123r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#810]
123r_1 begins with a list of ingredients that each has a dotted line to their amounts

In tc, the line breaks at least make the text look like a list, but in tcn and tl, the text is all one paragraph.

Should we introduce something to better represent the page?
e.g. add dash or period marks
or add the dashed lines as inline figures?

**Comment by njr2128** [comment]
For adding as inline figure, see the wavy line on 127v. Adding the dashed lines would be consistent with this treatment of a non-traditional line

**Comment by thuchacz** [comment]
DECISION AND WORK DONE:
I added <lb/> tags to the TL, since there is an open feature request to Nick to have <lb/> tags render in all three versions. Once Nick deals with this as well as the current problems with right margin block rendering, the TCN and TL should look something more like the TC currently does.

We can reassess if we want to represent a dashed or dotted line across the three versions in a subsequent render-check campaign.
