### ISSUE TITLE
markup update for entire entries that are deleted (p120v_3)?

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#835]
the entire entry is struck out but there are deletions within it that are not indicated. Some markup solutions should be found.

**Comment by njr2128** [comment]
UPDATE AND SUMMARY:
This has currently been dealt with only by editorial comment indication.
Previously, the markup for this entry had `<del>` tags around the entire entry. It was decided this was not sufficient (partly because it rendered in a way that was difficult to read, partly because it was decided that this kind of deletion is different from the current use/definition of `<del>`).

For the future, update encoding corpus to allow for this?
Marking as low priority and blocked for now

**Comment by njr2128** [comment]
This could also be used to "fix" #1598 (deleted figure)

**Comment by njr2128** [comment]
completed
