### ISSUE TITLE
Editorial comments on repeated words

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#842]
CAG and I had a few instances of words repeated in the original that have been carried over into the tcn and tl, as I think they should. I do not think we need editorial comments on these.  They are analogous to strike outs and additions, in my view.
@njr2128 : this is relevant to you in going through comments.

**Comment by njr2128** [comment]
I have come across a few instances of this or something similar (e.g., the word is repeated in the tc with a comment saying as much. The tcn has the repeated word, but the tl does NOT.)

I have flagged them in the comment tracking sheets, and we should definitely review as a group and make a decision to carry across the board

**Comment by njr2128** [comment]
DECISION until we review all editorial comments and compare markup across all versions:
If there is a repeated word, make sure there is an editorial comment.
We will then review the protocol (use of corr del, just editorial comment, which versions the word repetition should be carried into)

**Comment by thuchacz** [comment]
Scope of work:
@Pantagrueliste  to identify all doubles.
These must be assessed for false positives.
Where appropriate, add corr-del tag combos to TCN and TL.
Delete any editorial comments about this.

**Comment by Pantagrueliste** [comment]
using Regex `\b(\w+)\s+\1\b` on TC and TCN. Comparing results reveals transcription mistakes in TCN (16v, 38r, 157v) and in TC (48r)

**Comment by ps2270** [comment]
@Pantagrueliste did you tag all duplicates in tcn and tl? I see you did tcn 157v, but there were more, right? Thanks.

**Comment by Pantagrueliste** [comment]
Working on it

**Comment by Pantagrueliste** [comment]
Ref | Passage | Evaluation | Suggested correction
-- | -- | -- | --
tcn_p016v_preTEI.xml | `matiere, co<exp>mm</exp>e de deulx <ms>quintals</ms> ou de moings si tu n’en en pas tant,<lb/>` | Not intentional | `n’en <corr><del>en</del></corr> a pas tant`
tcn_p033r_preTEI.xml | force bons mots<lb/> de passe passe<lb/> affin qu’ilz le<lb/>` | Intentional |  
tcn_p034v_preTEI.xml | `Et plustost que faire ton jeu de passe passe, il fault que tu<lb/>` | Intentional |  
tcn_p038r_preTEI.xml | `leur naïfveté. J’en en ay un blanc qui semble estre brut &amp; percé, et est mouschetté<lb/>` | Not intentional | `J’en <corr><del>en</del></corr>ay un blanc`
tcn_p079r_preTEI.xml | `q<exp>ue</exp> vous vouldrés, &amp; aveq l’ayde<lb/> de <pn>Dieu</pn> <md>vous vous en trouverés fort bien</md>.</ab>` | Intentional |  
tcn_p086r_preTEI.xml | `de pœlonne</m>, il me raporta mes figures fort nettes. Il est<lb/> vray que j’avoys fort fort recuit mon <tl>chassis</tl>, il ne<lb/>` | Intentional |  
tcn_p109r_preTEI.xml | `<ab><margin>left-middle</margin>Oings fort fort<lb/> legerem<exp>ent</exp> d’<m>huile</m>` | Intentional |  
tcn_p113v_preTEI.xml | `le <del>a dista dista</del> avecq telle discretion qu’<del>` | Deleted |  
tcn_p121v_preTEI.xml | `<ab>Si les <pro>orfevres</pro> sçavoient sçavoient la matiere pour faire l’<m>argent</m><lb/>` | Not intentional |` <ab>Si les <pro>orfevres</pro> sçavoient <corr><del>sçavoient</del></corr> la matiere pour faire l’<m>argent</m><lb/>`
tcn_p146r_preTEI.xml | `du <m>sable destrempé</m> plus espés affin de faire faire<lb/> prise plustost. J’ay ainsy moulé un <pa>solcy</pa> avecq<lb/>` | Probably intentional | Leave as is
tcn_p149r_preTEI.xml | `&amp; pour ceste occasion la reparer, jecte la la pluspart d’<m>estaim</m><lb/>` | Not intentional | `jecte <corr><del>la</del></corr>la pluspart d’`
tcn_p150v_preTEI.xml | `jusques à ce qu’il soict bien bien plain jusques à<lb/>` | Not intentional | `soict <corr><del>bien</corr></del> bien plain`

**Comment by Pantagrueliste** [comment]
Note: I did not add `<corr></del>` tags to TL 16v and 38r.

**Comment by Pantagrueliste** [comment]
done

**Comment by Pantagrueliste** [comment]
editorial comments deleted
