### ISSUE TITLE
review and make consistent markup on 1r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#889]
The markup across versions is not the same for 1r (e.g., some divs are in margins in tc but not in tcn or tl)
Review positional markers across the versions and decide how to mark up consistently

**Comment by ps2270** [comment]
I've also noticed that punctuation is inconsistent.  We decided that these lists (because they will be rendered as lists) should NOT include any punctuation that the tc does not (e.g., an exception is when the the author is abbreviated in the tc).

Also, I thought we decided NOT to normalize these names since they will all have editorial comments anyway. They've all been expanded and normalized in tcn and tl, which I think is overdoing "translation".  But we can talk about this.

**Comment by thuchacz** [comment]
Update:
1. I have been experimenting with position of the blocks in the TC only; once we get the position markup right, I'll make the three versions consistent.
2. I have fixed the punctuation on 1r. See #757

**Comment by njr2128** [comment]
Collapse two divs into one (list of books and list of books+authors?)

Once done - let @njr2128 know so she can update DCE entry counts and categories

**Comment by njr2128** [comment]
Done!
(WOOHOO! A huge achievement completed by @thuchacz)
