### ISSUE TITLE
Next phase (3) of editorial comment review - markup

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#950]
To be completed after @ps2270 has completed her second pass through the comments

To do:
- pull complete list of comment anchors from xml files
- check that anchors have been entered correctly (no well-formedness errors, etc)
- identify comments that should be deleted (from tacking sheet) to then
- identify anchors that should be removed
- create list of anchors used more than once with their location (ie folio)

**Comment by ps2270** [comment]
I have completed my revision of comments.  I've tried to highlight (yellow) all that need attention (most of them the sic/markup issues, but I have NOT highlighted all of these!)
There are still a very few in orange, which I can't locate or otherwise couldn't decide about.
I've tried to institute the correct format for the ed comments: i.e., when it is more than a few words, I've capitalized the first letter and put a period at the end. And, I've made a stab at marking up italicized text, but did not finish it all.
We have some outstanding issues on which to decide:
#947 
#771 
#941 
- As soon as everyone weighs in on these, I'll attempt to make decisions.
- In addition, we have some comments that Marc needs to decide about.  It is not clear to me whether anyone has given him a list of issues he needs to answer??
- I believe CAG is still working on bibliography/titles?  I don't quite understand whether the machine-readable titles that are part of the bibliography will already be linked to these comments at the Edition's initial release?

**Comment by njr2128** [comment]
Refer to #984 as needed

**Comment by njr2128** [comment]
Working document for editorial comments: https://docs.google.com/spreadsheets/d/1SGJGb9PJzWNyhWN57EM4nwu2aKjkwabDgPNoizXG_lk/edit?usp=sharing

**Comment by njr2128** [comment]
For reference:
@njr2128, @thuchacz using this XPath expression to search files under ms-xml:

```
//comment[ not(. = doc('../../metadata/comment_ids_srt.xml')//id )]
```
(that is, comment elements whose text does not equal the text of an id element in the file metadata/comment_ids_srt.xml -- which I generated from metadata/DCE_comment-tracking-Tracking.csv)

**Comment by njr2128** [comment]
completed
