### ISSUE TITLE
121r - ups tags and editorial comment

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#951]
@thuchacz 
121r_1 has the famous cos or coin obscured by a paper strip, with the editorial comment:
"This word is obscured by the paper strip. It may be "cos," "coin," or otherwise. Context suggests it may refer to a vessel."
Should this have `<ups>` tags?  Does it not b/c it can't be read?
Thanks for checking on this.

**Comment by thuchacz** [comment]
please see closed issue #655.
both TT and CAG spent some time looking into possible meanings of "cos" and "cois," to no conclusive avail.

MHS said that it certainly wasn't "coin." If "cos," the whole word is visible. He couldn't really see anything conclusive under the paper strip, and he thought that, at most, it could be "cois" but certainly not "coin." So... because we've left it as "cos," there are no `<ups>` tags. Perhaps the editorial comment can be changed to read: **Word unclear. It may be partially** obscured by the paper strip. It may be "cos," "coin," or otherwise. Context suggests it may refer to a vessel.

**Comment by ps2270** [comment]
Thanks.  Changed the comment.
