### ISSUE TITLE
Regularise translation of "gros(se)" and "grossier"

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#98]
Search "gros(se)" and "grossier".

Translate "gros/grosse" as “coarse” (e.g. sand) or “thick”/”big” depending on context.

Determine whether "grossier" is used differently and should be translated differently. E.g. does it seem to have a moral or aesthetic dimension along the lines of "vulgar"?

**Comment by TillmannTaape** [comment]
24r. "metal fin" vs "metal gros" translated as "fine metal" vs "coarse metal" – @ps2270 does that sound ok?

**Comment by ps2270** [comment]
What is "coarse metal"? How many instances of "metal gros" are there?

**Comment by TillmannTaape** [comment]
24r is the only instance.

"Metal fin" has more copper (see below), so by impliction "metal gros" probably is an alloy with less (or no) copper. This is discussed in the context of making grenades:

"Les grenades doibvent estre du <m>plus fin metal qu’on puysse
trouver</m>,<lb/>
car il y a <m>metal fin</m> et <m>metal gros</m>. Le <m>metal fin</m>
est celuy de grosse<lb/>
cloche, pour ce que on y mect plus de <m>cuivre</m> pour luy donner la
voix<lb/>
plus grosse, &amp; aulx petites cloches on mect plus d’<m>estain</m>
pour luy<lb/>
donner le son plus <del>gros</del> clair. Le <m>metal de grosse
cloche</m> se faict<lb/>
d<del>’un</del><add>e 3</add> <ms>quintal</ms><add>z</add> de
<m>rosette</m> &amp; vint ou xxv <ms>lb</ms> d’<m>estain</m>."

**Comment by ps2270** [comment]
I think "crude" is better than coarse. I hate to raise this, but this brings up once again the problem of whether fin is better translated in this case by pure. The "finest" metal one can find is rather different than the "purest". This entry seems pretty clearly to mean the purest _metal_ (in the sense of copper alloy "metal", not generic metal), because it goes on to say that finest means a larger amount of copper. I'm not sure how to deal with this.  Have we used pure to translate "fin" in the case of silver and tin? I'm pretty sure we have, but it's worth searching selectively.  It might be better to use "pure" and "crude" in this instance.  Sorry!

**Comment by TillmannTaape** [comment]
"grosserie" of goldsmiths (often paired with "vaisselle", i.e. plate) is variously translated as "wholesale" or "grand work". Any ideas what this means and how to translate?
@Pantagrueliste ? @ps2270 ?

**Comment by TillmannTaape** [comment]
Finished searching and checking for gros(se)*/grossier. Leaving the issue open until we've figured out "grosserie" (see above).

Updated vocab entry:
Gros, grosse (adj.) = “coarse” (e.g. sand)/”rough” (e.g. cloth) or “thick”/”big”/“large” depending on context
p058_4 margin. See Cotgrave: gross, thick, blockish etc. (TT CD)
	if describing an amount, e.g. “aussi gros comme une feve” = “as much as a bean”
	“metal gros” as opposed to “metal fin” = “crude metal” (24r)
Grosset (adj.) = “thickish” or “largeish”
Grossier = “coarse”/”crude” (e.g. turpentine, 3v)
Grosseur = “size” e.g. in the size of a walnut etc.

**Comment by TillmannTaape** [comment]
Actually I'm closing this one and creating new issue for "grosserie"
